version: "3"

services:

  mongo:
    image: "mongo"
    container_name: "mongo"
    ports:
      - "27018:27017"
    volumes:  
      - E:\DB\Data:/data/db
      - E:\DB\Config:/data/config

  redis:
    image: "redis"
    container_name: "redis"

  web:
    image: "img_jbapi"
    container_name: "jbwebapi"
    ports:
      - "82:82"
    environment:
      MongoDB__Host: mongo      
    depends_on:
      - mongo   
