version: "3"

services:

  mongo:
    image: "mongo"
    container_name: "mongo"
    ports:
      - "27018:27017"

  web:
    image: "img_jbapi"
    container_name: "jbwebapi"
    ports:
      - "82:82"
    environment:
      MongoDB__Host: mongo      
    depends_on:
      - mongo      
